interface - help
helpProd
	"prints help intro to Transcript"

	Transcript
		show: '  Products:';
		cr.
	Transcript
		show: '     Add  -  addProdWithKey:';
		cr.
	Transcript
		show: '     Add  -  addProdWithKey:Desc:Price:';
		cr.
	Transcript
		show: '     View  -  viewProd:';
		cr.
	Transcript
		show: '     View all  -  viewAllProducts';
		cr.
	Transcript
		show: '     Search by description  -  searchProdByDesc:';
		cr.
	Transcript
		show: '     Update description  -  updateProd:WithDesc:';
		cr.
	Transcript
		show: '     Update price  -  updateProd:WithPrice:';
		cr.
	Transcript
		show: '     Delete  -  deleteProd:';
		cr